apiVersion: v1
kind: Service
metadata:
  name: play-http-client
spec:
  ports:
    - 
      name: svc-9000
      port: 9000
      protocol: TCP
      targetPort: 9000
    - 
      name: svc-2555
      port: 2555
      protocol: TCP
      targetPort: 2555
  selector:
    run: play-http-client
    deploymentconfig: play-http-client
  sessionAffinity: None
  type: ClusterIP
  clusterIP: 172.30.0.13
  portalIP: 172.30.0.13